version: "3.8"

services:
  app:
    build: .
    container_name: llm-wordle-arena
    restart: unless-stopped
    ports:
      - "${PORT:-8080}:8080"
    env_file:
      - .env
    volumes:
      - ./results:/app/results
